//TESTE DE REQUISIÇÕES REST
@baseURL = http://localhost:4000
@id = 6272d2b24f7870dc2f7c65b2

###
//GET - Lista todas os usuarios
GET {{baseURL}}/cursos/{{id}}
Content-Type: application/json



###
//POST Login
PUT {{baseURL}}/cursos
Content-Type: application/json

{
    "_id":"6272d2b24f7870dc2f7c65b2",
    "nome":"danilo"
}

