//TESTE DE REQUISIÇÕES REST
@baseURL = http://localhost:4000
@id = 619d068ef455b2ded14c3af4

###
//GET - Lista todas os usuarios
GET {{baseURL}}/usuarios
Content-Type: application/json


###
//POST - Incluir um novo usuario
POST {{baseURL}}/usuarios
Content-Type: application/json

{
    "nome": "murilo"
}




###
//DELETE - Excluir usuario  
DELETE {{baseURL}}/usuarios/{{id}}
Content-Type: application/json


###
// PUT - Alterar um usuario
PUT {{baseURL}}/usuarios/{{id}}


